# Generated by Django 5.1.3 on 2024-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='contact',
            field=models.IntegerField(default='12345678'),
            preserve_default=False,
        ),
    ]
