# Generated by Django 5.1.3 on 2024-12-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupApp', '0002_signup_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='qualigication',
            new_name='qualification',
        ),
    ]
